language: node_js
node_js:
  - '0.10'
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem update --system
  - gem install compass
before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
